// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/statuspage-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"component | component_group_uptime | group_component | incident | incident_postmortem | incident_subscriber | incident_template | incident_update | metric | metrics_provider | page | page_access_group | page_access_user | permission | postmortem | status_embed_config | subscriber | user"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.StatuspageSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "statuspage_list",
		Description: "List records from Statuspage. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "statuspage_load",
		Description: "Load a single record from Statuspage. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.StatuspageSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.StatuspageSDK, name string) (sdk.StatuspageEntity, error) {
	switch strings.ToLower(name) {
	case "component":
		return client.Component(nil), nil
	case "component_group_uptime":
		return client.ComponentGroupUptime(nil), nil
	case "group_component":
		return client.GroupComponent(nil), nil
	case "incident":
		return client.Incident(nil), nil
	case "incident_postmortem":
		return client.IncidentPostmortem(nil), nil
	case "incident_subscriber":
		return client.IncidentSubscriber(nil), nil
	case "incident_template":
		return client.IncidentTemplate(nil), nil
	case "incident_update":
		return client.IncidentUpdate(nil), nil
	case "metric":
		return client.Metric(nil), nil
	case "metrics_provider":
		return client.MetricsProvider(nil), nil
	case "page":
		return client.Page(nil), nil
	case "page_access_group":
		return client.PageAccessGroup(nil), nil
	case "page_access_user":
		return client.PageAccessUser(nil), nil
	case "permission":
		return client.Permission(nil), nil
	case "postmortem":
		return client.Postmortem(nil), nil
	case "status_embed_config":
		return client.StatusEmbedConfig(nil), nil
	case "subscriber":
		return client.Subscriber(nil), nil
	case "user":
		return client.User(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
